/**
 * F1.3 document round-trip contract.
 *
 * Runs three layered properties:
 *
 *   1. Canonical fixture (`example.aqua.json`) round-trips through serialize →
 *      loadAquaDocument unchanged.
 *   2. fast-check property: any AquaDocument generated by `arbAquaDocument`
 *      survives JSON serialize/parse losslessly.
 *   3. fast-check property: the same documents survive ZIP container pack/load.
 *
 * This file is what the CI `document-round-trip` job runs:
 *   `pnpm exec nx test testing -t document-round-trip`
 *
 * The `-t document-round-trip` filter matches Jest's `describe('document-round-trip')`
 * blocks below, so adding more files to this lib will not slow the gate down.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import fc from 'fast-check';

import type { AquaDocument } from '@aquascape/domain/document';
import {
  loadAquaDocument,
  packAquaDocument,
  serializeAquaDocument,
} from '@aquascape/domain/document';

import { arbAquaDocument } from './arbitraries/aqua-document';

const EXAMPLE: AquaDocument = JSON.parse(
  readFileSync(resolve(__dirname, '../../../example.aqua.json'), 'utf8'),
);

describe('document-round-trip', () => {
  it('canonical example.aqua.json round-trips through serialize → loadAquaDocument', () => {
    const json = serializeAquaDocument(EXAMPLE);
    const loaded = loadAquaDocument(json);
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    expect(loaded.document).toEqual(EXAMPLE);
  });

  it('canonical example.aqua.json round-trips through ZIP pack → loadAquaDocument', () => {
    const bytes = packAquaDocument(EXAMPLE);
    const loaded = loadAquaDocument(bytes);
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    expect(loaded.document).toEqual(EXAMPLE);
    expect(loaded.source).toBe('zip');
  });

  it('property: any AquaDocument round-trips through JSON', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        const loaded = loadAquaDocument(serializeAquaDocument(doc));
        expect(loaded.ok).toBe(true);
        if (!loaded.ok) return;
        expect(loaded.document).toEqual(doc);
      }),
      { numRuns: 100 },
    );
  });

  it('property: any AquaDocument round-trips through the ZIP container', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        const loaded = loadAquaDocument(packAquaDocument(doc));
        expect(loaded.ok).toBe(true);
        if (!loaded.ok) return;
        expect(loaded.document).toEqual(doc);
        expect(loaded.source).toBe('zip');
      }),
      { numRuns: 50 },
    );
  });

  it('property: a v2 document migrates to v3 without inventing tank.waterLevelMm', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        // Rewind an arbitrary current-version doc to a structurally-valid v2
        // doc: strip the v3-only field and stamp the old version.
        const { waterLevelMm: _stripped, ...tankNoLevel } = doc.tank;
        const v2Doc = { ...doc, schemaVersion: 2, tank: tankNoLevel };
        const loaded = loadAquaDocument(serializeAquaDocument(v2Doc as AquaDocument));
        expect(loaded.ok).toBe(true);
        if (!loaded.ok) return;
        expect(loaded.document.schemaVersion).toBe(3);
        // Absent stays absent — the v2 → v3 step is a version-stamp
        // pass-through and must NOT materialise the render-time default fill.
        expect('waterLevelMm' in loaded.document.tank).toBe(false);
        expect({ ...loaded.document, schemaVersion: 2 }).toEqual(v2Doc);
      }),
      { numRuns: 50 },
    );
  });

  it('property: JSON.parse(JSON.stringify(doc)) is lossless (the format invariant)', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        expect(JSON.parse(JSON.stringify(doc))).toEqual(doc);
      }),
      { numRuns: 100 },
    );
  });
});
