/**
 * F1.3 document round-trip contract.
 *
 * Runs three layered properties:
 *
 *   1. Canonical fixture (`example.aqua.json`) round-trips through serialize →
 *      loadAquaDocument unchanged.
 *   2. fast-check property: any AquaDocument generated by `arbAquaDocument`
 *      survives JSON serialize/parse losslessly.
 *   3. fast-check property: the same documents survive ZIP container pack/load.
 *
 * This file is what the CI `document-round-trip` job runs:
 *   `pnpm exec nx test testing -t document-round-trip`
 *
 * The `-t document-round-trip` filter matches Jest's `describe('document-round-trip')`
 * blocks below, so adding more files to this lib will not slow the gate down.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import fc from 'fast-check';

import type { AquaDocument } from '@aquascape/domain/document';
import {
  loadAquaDocument,
  packAquaDocument,
  serializeAquaDocument,
} from '@aquascape/domain/document';

import { arbAquaDocument } from './arbitraries/aqua-document';

const EXAMPLE: AquaDocument = JSON.parse(
  readFileSync(resolve(__dirname, '../../../example.aqua.json'), 'utf8'),
);

describe('document-round-trip', () => {
  it('canonical example.aqua.json round-trips through serialize → loadAquaDocument', () => {
    const json = serializeAquaDocument(EXAMPLE);
    const loaded = loadAquaDocument(json);
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    expect(loaded.document).toEqual(EXAMPLE);
  });

  it('canonical example.aqua.json round-trips through ZIP pack → loadAquaDocument', () => {
    const bytes = packAquaDocument(EXAMPLE);
    const loaded = loadAquaDocument(bytes);
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    expect(loaded.document).toEqual(EXAMPLE);
    expect(loaded.source).toBe('zip');
  });

  it('property: any AquaDocument round-trips through JSON', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        const loaded = loadAquaDocument(serializeAquaDocument(doc));
        expect(loaded.ok).toBe(true);
        if (!loaded.ok) return;
        expect(loaded.document).toEqual(doc);
      }),
      { numRuns: 100 },
    );
  });

  it('property: any AquaDocument round-trips through the ZIP container', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        const loaded = loadAquaDocument(packAquaDocument(doc));
        expect(loaded.ok).toBe(true);
        if (!loaded.ok) return;
        expect(loaded.document).toEqual(doc);
        expect(loaded.source).toBe('zip');
      }),
      { numRuns: 50 },
    );
  });

  it('property: a v2 document migrates to v5 without inventing tank.waterLevelMm / waterChemistry', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        // Rewind an arbitrary current-version doc to a structurally-valid v2
        // doc: strip the v3-only (`waterLevelMm`) and v4-only
        // (`waterChemistry`) fields and stamp the old version.
        const {
          waterLevelMm: _strippedLevel,
          waterChemistry: _strippedChem,
          ...tankV2
        } = doc.tank;
        const v2Doc = { ...doc, schemaVersion: 2, tank: tankV2 };
        const loaded = loadAquaDocument(serializeAquaDocument(v2Doc as AquaDocument));
        expect(loaded.ok).toBe(true);
        if (!loaded.ok) return;
        expect(loaded.document.schemaVersion).toBe(5);
        // Absent stays absent through the whole v2 → v3 → v4 → v5 chain — the
        // additive steps are version-stamp pass-throughs and must NOT
        // materialise a default; the v5 step strips renderHistory (absent here).
        expect('waterLevelMm' in loaded.document.tank).toBe(false);
        expect('waterChemistry' in loaded.document.tank).toBe(false);
        expect({ ...loaded.document, schemaVersion: 2 }).toEqual(v2Doc);
      }),
      { numRuns: 50 },
    );
  });

  it('property: a v3 document migrates to v5 without inventing tank.waterChemistry', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        // Rewind an arbitrary current-version doc to a structurally-valid v3
        // doc: strip only the v4-only `waterChemistry` field (the v3
        // `waterLevelMm` is valid under v3 and may be present or absent).
        const { waterChemistry: _stripped, ...tankV3 } = doc.tank;
        const v3Doc = { ...doc, schemaVersion: 3, tank: tankV3 };
        const loaded = loadAquaDocument(serializeAquaDocument(v3Doc as AquaDocument));
        expect(loaded.ok).toBe(true);
        if (!loaded.ok) return;
        expect(loaded.document.schemaVersion).toBe(5);
        // Absent stays absent — the v3 → v4 step is a version-stamp
        // pass-through and must NOT invent a cycle history.
        expect('waterChemistry' in loaded.document.tank).toBe(false);
        expect({ ...loaded.document, schemaVersion: 3 }).toEqual(v3Doc);
      }),
      { numRuns: 50 },
    );
  });

  it('property: a v4 document carrying renderHistory migrates to v5 with the field stripped', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        // Stamp an arbitrary current-version doc back to v4 and attach a
        // renderHistory bag (the now-retired AI-render field). The v4 schema is
        // a structural superset of v5 minus this field, so the doc is a valid
        // v4 document. The v4 → v5 step must strip renderHistory so it loads
        // cleanly under the v5 schema's `additionalProperties: false`.
        const v4Doc = {
          ...doc,
          schemaVersion: 4,
          renderHistory: [
            {
              id: '11111111-0000-4000-8000-000000000001',
              createdAt: '2026-05-23T15:00:00.000Z',
              provider: { kind: 'local', name: 'sdxl-local' },
              request: { prompt: 'a tank' },
              resultAsset: {
                id: '11111111-0000-4000-8000-000000000002',
                uri: 'assets/render.png',
                mimeType: 'image/png',
              },
            },
          ],
        };
        const loaded = loadAquaDocument(serializeAquaDocument(v4Doc as AquaDocument));
        expect(loaded.ok).toBe(true);
        if (!loaded.ok) return;
        expect(loaded.document.schemaVersion).toBe(5);
        // The dropped field is GONE; everything else carries through unchanged.
        expect('renderHistory' in loaded.document).toBe(false);
        const { renderHistory: _dropped, ...v4Rest } = v4Doc;
        expect({ ...loaded.document, schemaVersion: 4 }).toEqual(v4Rest);
      }),
      { numRuns: 50 },
    );
  });

  it('property: JSON.parse(JSON.stringify(doc)) is lossless (the format invariant)', () => {
    fc.assert(
      fc.property(arbAquaDocument(), (doc) => {
        expect(JSON.parse(JSON.stringify(doc))).toEqual(doc);
      }),
      { numRuns: 100 },
    );
  });
});
